package com.libmanagement.model;
// Generated May 26, 2014 12:53:03 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * BookAuthors generated by hbm2java
 */
@Entity
@Table(name = "book_authors")
public class BookAuthors implements java.io.Serializable {

    @Id
    @Column
    private String bookId;
    @OneToOne
    private Book book;
    @Column
    private String authorsName;

    public BookAuthors() {
    }

    public BookAuthors(String bookId, Book book, String authorsName) {
        this.bookId = bookId;
        this.book = book;
        this.authorsName = authorsName;
    }

    public String getBookId() {
        return this.bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public Book getBook() {
        return this.book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public String getAuthorsName() {
        return this.authorsName;
    }

    public void setAuthorsName(String authorsName) {
        this.authorsName = authorsName;
    }
}
