package com.libmanagement.model;
// Generated May 26, 2014 12:53:03 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;




/**
 * BookCopies generated by hbm2java
 */
@Entity
@Table(name = "book_copies")
public class BookCopies  implements java.io.Serializable {

    @Id
    @Column
     private int bookCopyId;
     private LibraryBranch libraryBranch;
    @OneToOne
     private Book book;
    @Column
     private String noOfCopies;

    public BookCopies() {
    }

    public BookCopies(int bookCopyId, LibraryBranch libraryBranch, Book book, String noOfCopies) {
       this.bookCopyId = bookCopyId;
       this.libraryBranch = libraryBranch;
       this.book = book;
       this.noOfCopies = noOfCopies;
    }
   
    public int getBookCopyId() {
        return this.bookCopyId;
    }
    
    public void setBookCopyId(int bookCopyId) {
        this.bookCopyId = bookCopyId;
    }
    public LibraryBranch getLibraryBranch() {
        return this.libraryBranch;
    }
    
    public void setLibraryBranch(LibraryBranch libraryBranch) {
        this.libraryBranch = libraryBranch;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public String getNoOfCopies() {
        return this.noOfCopies;
    }
    
    public void setNoOfCopies(String noOfCopies) {
        this.noOfCopies = noOfCopies;
    }




}


