package com.libmanagement.model;
// Generated May 26, 2014 12:53:03 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LibraryBranch generated by hbm2java
 */
@Entity
@Table(name = "library_branch")
public class LibraryBranch implements java.io.Serializable {

    @Id
    @Column
    private int branchId;
    @Column
    private String branchName;
    @Column
    private String address;
    private Set bookCopieses = new HashSet(0);
    private Set bookLoanses = new HashSet(0);

    public LibraryBranch() {
    }

    public LibraryBranch(int branchId) {
        this.branchId = branchId;
    }

    public LibraryBranch(int branchId, String branchName, String address, Set bookCopieses, Set bookLoanses) {
        this.branchId = branchId;
        this.branchName = branchName;
        this.address = address;
        this.bookCopieses = bookCopieses;
        this.bookLoanses = bookLoanses;
    }

    public int getBranchId() {
        return this.branchId;
    }

    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    public String getBranchName() {
        return this.branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Set getBookCopieses() {
        return this.bookCopieses;
    }

    public void setBookCopieses(Set bookCopieses) {
        this.bookCopieses = bookCopieses;
    }

    public Set getBookLoanses() {
        return this.bookLoanses;
    }

    public void setBookLoanses(Set bookLoanses) {
        this.bookLoanses = bookLoanses;
    }
}
